baseURL = 'https://beau.so/'
languageCode = 'en-us'
title = '/'
theme = "b"
sectionPagesMenu = "main"
summaryLength = 70

[params]
  author = "beau"
  
[markup.highlight]
      codeFences = true
      guessSyntax = true
      lineNos = true
      lineNumbersInTable = true
      tabWidth = 2
      noClasses = false
